# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f792830727a5a7a184fe7c707c5c6d4b66571e194d147fd7b68168846d6061b2673b8ba61383cefcffc36c4d0c1f8cb0f8a2d4711610235a7e802676efff64b0

test:
  secret_key_base: ecddfdf01a7aba503b70316623bb0d72f4bafb0d79d3c4c2c1d2af8c198d1b93caebcb93d56e094afed346f2b084349bab9c7fac21cdb367fd511cb776efe629

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
